[package]
name = "mt_treewalk"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
crossbeam = "0.8.4"
nix = { version = "0.29.0", features = ["dir", "fs"] }
